### ISSUE TITLE
Copy functionality does not work as expected

### ISSUE THREAD

**Issue by teobais** [javierbyte/cohesive-colors#6]
Only the initial provided "result colors" can be copied to clipboard.

That is, if user changes either the overlay color or the intensity of it, the results are not updated with the new hex values; they remain the same as in the very first load of the page.

<em>The on hover functionality seems to be working fine. Values are updated but not properly copied</em>

**Comment by javierbyte** [comment]
@toubou91 you are right! thank you! this is fixed and deployed now!
