### ISSUE TITLE
How can i use it on jquery

### ISSUE THREAD

**Issue by sifulbd** [javierbyte/cohesive-colors#7]
Hi, Is there any way to use at on jqiery?

**Comment by javierbyte** [comment]
@sifulbd yes, use this script https://github.com/javierbyte/colorblendjs/blob/master/index.js and then `var resultColor = colorBlend.overlay(firstColor, secondColor, intensity);` in which `firstColor` and `secondColor` are rgb arrays (`[r, g, b]`, for example `[160, 179, 197]`).

**Comment by sifulbd** [comment]
wow. Thanks for immediate response. can you provide me a demo like codepen.io or jsfiddle? 
its helps me to understand. 

Regards,

**Comment by javierbyte** [comment]
@sifulbd see https://github.com/javierbyte/colorblendjs/blob/gh-pages/index.html#L72

**Comment by sifulbd** [comment]
tried but its not working like cohesive-colors. all the component is not working like this one.

**Comment by sifulbd** [comment]
@javierbyte I wanted similar like, click to open color plate and change opacity. also add more color and remove. is it possible?

**Comment by javierbyte** [comment]
@sifulbd ah! I understand now. That is out of the scope of this project. The real thing is https://github.com/javierbyte/colorblendjs a lib to apply the color overlay, this repo (including the color picker etc) it's only a demo for the colorblendjs.
